services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    

  client:
    build: ./client
    ports:
      - "5173:80"
    environment:
      - VITE_SERVER_URL=http://localhost:3001
    depends_on:
      - server
    
